import { expect, it } from 'vitest'
import { calculate, type SubnetInfo } from '../src/subnet'

type Case = Omit<SubnetInfo, 'prefix'> & { ip: number; prefix: number }

// cases.json is generated by scripts/gen_cases.py (npm pretest) and not committed
const cases = Object.values(import.meta.glob<Case[]>('./cases.json', { eager: true, import: 'default' }))[0]

it('matches Python ipaddress on generated cases', () => {
  expect(cases, 'cases.json missing, run: python3 scripts/gen_cases.py').toBeDefined()
  for (const { ip, ...expected } of cases ?? []) expect(calculate(ip, expected.prefix)).toEqual(expected)
})
